version: "3.1"

services:
  tomcat:
    container_name: tomcat
    build: ../alterUber_backend/alterUber_service
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - ubernet
    restart: unless-stopped

  db:
    container_name: mysql
    build: ../eCommerce_DB
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql/data
    networks:
      - ubernet
    restart: unless-stopped
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: ecommerce
       MYSQL_PASSWORD: eCom@di2018

volumes:
  data:
    driver: local

networks:
  ubernet:
    driver: bridge